-- Ce fichier ne porte plus de contenu.
--
-- Le chapitre 1 vit dans une MIGRATION datée
-- (`supabase/migrations/*_contenu_chapitre_1.sql`), générée depuis
-- `docs/chapitre-1-v3.2.md`.
--
-- Pourquoi : un seed initialise une base vide, et la CLI refuse de le rejouer
-- une fois son empreinte enregistrée. Le contenu, lui, évolue à chaque chapitre
-- et à chaque correction de ton — le laisser ici obligeait à contourner la CLI
-- à chaque publication.
--
-- ⚠️ **Ne pas y remettre de contenu.** Ça marcherait en local, où `db reset`
-- rejoue tout, et échouerait silencieusement sur l'hébergé — exactement le
-- piège dans lequel on est tombé le 17 août 2026.
--
-- Voir docs/ARCHITECTURE.md § Le contenu se déploie par migration.
